### ISSUE TITLE
eslint?

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/niftany#11]
Hey @awead - ever consider adding a JS lint to the equation? I just added es-lint myself (think we talked about this briefly at a refactor friday) and was thinking about how it would probably work nicely in niftany.

**Comment by awead** [comment]
Yeah, I added that to cho, but I did that in the context of yarn and `package.json` and I'm not sure how I'd do that within a ruby gem. Any ideas?

**Comment by cdmo** [comment]
It doesn't fit neatly, I see what you mean.

You'd have to have add a `package.json` and add `yarn` as a pre-requisite and part of the install process (actually running yarn once installed). In the niftany command (`exe/niftany`) I guess you could add a system call like `\`yarn lint\`` - but that's a pretty naive approach compared to how you have the other linters running. Maybe add a system check for node_modules? You'd also have to have an `.exlintrc` type file present too. 

I don't know, maybe adding too much weight. But, at the same time, a JavaScript linter would be nice.

Anyway, just spitballing.

**Comment by awead** [comment]
We could do a niftany npm package...

**Comment by cdmo** [comment]
I like that idea. Tangent: I was also thinking about `jest` and how it wouldn't be a good fit for the goals of niftany (probably). But, might be nice to have a kinda of JavaScript Starter Pack kind of thing. Or, just keep it simple and make a niftany-js kind of package that would be just about linting. Again, thinking outloud. Idunno.

**Comment by awead** [comment]
Yeah, I'm down with Jest. I set that up in CHO (along with the above-mentioned linter), but didn't really follow through with the test.

**Comment by cdmo** [comment]
Closing this, can make a npm package some day if we're up to it perhaps
